- src/BL/Services/KeycloakTokenHelper.cs
- src/DARE-API/Services/KeyclockTokenAPIHelper.cs
add proxy to second helper class
> feat: added proxy to second class

- src/DARE-API/Program.cs
- src/DARE-API/appsettings.json
make database seeding optional - issue with minio stopping anything from working
> feat: optional seeding

- src/BL/Models/Settings/BaseKeyCloakSettings.cs
- src/DARE-API/Program.cs
- src/DARE-API/Services/KeycloakMinioUserService.cs
- src/DARE-API/Services/KeyclockTokenAPIHelper.cs
add http handler (including proxy) into base class and use on httpclient initialisation in keycloak handler
> feat: Minio handle proxy

- src/TRE-API/Controllers/SubmissionCredentialsController.cs
- src/TRE-API/DoAgentWork.cs
- src/TRE-API/JobSettings.cs
- src/TRE-API/Program.cs
- src/TRE-API/appsettings.json
fix issue with EF
move some settings to app settings
> feat: Fix ef issue

- src/DARE-API/Dockerfile
- src/DARE-FrontEnd/Dockerfile
- src/Data-Egress-API/Dockerfile
- src/Data-Egress-UI/Dockerfile
- src/TRE-API/Dockerfile
- src/TRE-UI/Dockerfile
- src/TREAgent/Dockerfile
- src/Tre-Hasura/Dockerfile
This reverts commit 2b48d24e485549a8a300161f014694df5f4b49a0.
> Revert "chore(deps): update dotnet monorepo to v8 (major) (#122)"

- src/BL/Models/Project.cs
- src/BL/Models/ViewModels/ProjectUserTre.cs
- src/DARE-API/Migrations/20231115114222_addedownerandcontacttoproject.Designer.cs
- src/DARE-API/Migrations/20231115114222_addedownerandcontacttoproject.cs
- src/DARE-API/Migrations/20231115114706_addedownerandcontacttoprojectusertre.Designer.cs
- src/DARE-API/Migrations/20231115114706_addedownerandcontacttoprojectusertre.cs
- src/DARE-FrontEnd/Controllers/ProjectController.cs
- src/DARE-FrontEnd/Views/Project/GetAllProjects.cshtml
- src/DARE-FrontEnd/Views/Project/GetProject.cshtml
Made it so that if the field doesn't exist the html isn't there. Changed last updated text. Ran migrations to add in project owner and contact and displayed these on the ui, changed layout of the dates
> Feat: frontendchanges UI

- src/TRE-UI/Controllers/AccountController.cs
add proper account controller actions
> feat: add account controller

- src/DARE-FrontEnd/Controllers/SubmissionController.cs
Removes Unneeded input for tes
> Removes Unneeded input for tes

- src/BL/Models/User.cs
- src/DARE-API/Controllers/UserController.cs
- src/DARE-API/Migrations/20231211172116_fullName.Designer.cs
- src/DARE-API/Migrations/20231211172116_fullName.cs
- src/DARE-FrontEnd/Controllers/ProjectController.cs
- src/DARE-FrontEnd/Views/Project/GetProject.cshtml
- src/DARE-FrontEnd/Views/Submission/GetAllSubmissions.cshtml
- src/TRE-UI/Views/Approval/GetAllProjects.cshtml
Formatted the table for getllprojects 
changed order of the table and added in links
added a fullname field to form.io and ran migrations
changed proj description to be what it needs to be
Changed default ordering of tables
> Feat: Working on the list of UI changes info in desc

- .github/workflows/api-container.yaml
- .github/workflows/egress-api-container.yaml
- .github/workflows/egress-ui-container.yaml
- .github/workflows/tre-api-container.yaml
- .github/workflows/tre-hasura-container.yaml
- .github/workflows/tre-ui-container.yaml
- .github/workflows/ui-container.yaml
See https://github.com/SwanseaUniversityMedical/workflows/pull/127
> fix: fixes bug where release pipeline failed silently when no conventional commits were found that would trigger a release

- src/DARE-FrontEnd/Controllers/SubmissionController.cs
> fix: testing addi

- src/DARE-FrontEnd/Controllers/SubmissionController.cs
- src/DARE-FrontEnd/Models/URLSettingsFrontEnd.cs
- src/Data-Egress-UI/Controllers/DataController.cs
- src/Data-Egress-UI/Controllers/HomeController.cs
- src/Data-Egress-UI/Views/Data/GetAllEgressesuUnprocessed.cshtml
> fix(deps): show only EgressUnprocessed on mine page

- src/TRE-API/Controllers/TRECredentialsController.cs
- src/TRE-UI/Controllers/TRECredentialsController.cs
- src/TRE-UI/Views/Shared/_Layout.cshtml
- src/TRE-UI/Views/TRECredentials/UpdateCredentials.cshtml
> fix(deps): add TRE Credentials to TRE UI

- src/DARE-API/Controllers/TESController.cs
> fix: debug

- src/DARE-API/Controllers/TESController.cs
> fix(deps): to sort out joss weird deploy stuff

- src/DARE-API/Controllers/TESController.cs
> fix(deps): remove debug

- src/BL/Models/ViewModels/ProjectUserTre.cs
- src/BL/Models/ViewModels/SubmissionList.cs
- src/DARE-API/Controllers/ProjectController.cs
- src/DARE-API/Controllers/TreController.cs
- src/DARE-API/Controllers/UserController.cs
- src/DARE-FrontEnd/Controllers/ProjectController.cs
- src/DARE-FrontEnd/Views/Project/GetProject.cshtml
- src/DARE-FrontEnd/Views/Shared/_SubmissionList.cshtml
- src/bl/Models/SubmissionGetProjectModel.cs
> fix(deps): Fix/john/optimisationtest (to branch fix/john/NeedToDecrypt)

- docker-compose.yml
> fix(deps): Docker compose

- src/TRE-API/Services/IKeyCloakService.cs
> fix: No Spaces In Key Cloak Name

- src/BL/Models/Tes/TesTask.cs
- src/DARE-FrontEnd/Controllers/SubmissionController.cs
> fix: broken sub wiz

- src/TRE-API/Services/DareClientWithoutTokenHelper.cs
> fix: correct role type

- src/TRE-API/DoAgentWork.cs
> fix: testing

- src/TRE-API/DoAgentWork.cs
> fix: more testing

- src/BL/Services/MinioHelper.cs
> fix: build damnit

- src/BL/Services/MinioHelper.cs
> fix: more debgu

- src/BL/Services/MinioHelper.cs
> fix: proxy

- src/BL/Services/MinioHelper.cs
> fix: getobject has been added to bucket policy

- src/DARE-API/Services/KeycloakMinioUserService.cs
> fix: crashes

- src/BL/Models/SubmissionGetProjectModel.cs
> fix: broken tre

- src/DARE-FrontEnd/Controllers/SubmissionController.cs
> fix: there

- src/DARE-API/Services/ConsumeInternalMessageService.cs
> fix: one more step

- src/DARE-API/Services/ConsumeInternalMessageService.cs
> fix: idiot

- src/DARE-API/Services/ConsumeInternalMessageService.cs
> fix: arrgh

- src/DARE-API/Services/ConsumeInternalMessageService.cs
> fix: dfgdfgsdfgsdfgsdfg

- src/BL/Services/BaseClientHelper.cs
- src/TRE-API/Services/DareClientWithoutTokenHelper.cs
> fix: damit

- src/BL/Services/BaseClientHelper.cs
- src/TRE-API/Services/DareClientWithoutTokenHelper.cs
> fix: sdfsdfsd

- src/BL/Services/BaseClientHelper.cs
> fix: remove debug

- src/TRE-UI/Program.cs
> fgdfgdfgff

- .github/renovate.js
Adjust renovate schedule to suggest ci workflow bumps at any time.
> ci: adjust renovate schedule to suggest workflow updates at any time

- src/TRE-API/Program.cs
- src/TRE-UI/Program.cs
> fix tidy up

- src/BL/Services/BaseClientHelper.cs
> fix remove

- src/DARE-API/Program.cs
- src/DARE-API/appsettings.json
- src/DARE-FrontEnd/Program.cs
- src/DARE-FrontEnd/appsettings.json
- src/Data-Egress-API/Program.cs
- src/Data-Egress-API/appsettings.json
- src/Data-Egress-UI/Program.cs
- src/Data-Egress-UI/appsettings.json
- src/TRE-API/Program.cs
- src/TRE-API/appsettings.json
- src/TRE-UI/Program.cs
- src/TRE-UI/appsettings.json
> fix: add forgery token suprress

- src/DARE-API/Program.cs
- src/DARE-FrontEnd/Program.cs
- src/Data-Egress-API/Program.cs
- src/Data-Egress-UI/Program.cs
- src/TRE-API/Program.cs
- src/TRE-UI/Program.cs
> fix: forgery warnng

- src/BL/Models/Settings/BaseKeyCloakSettings.cs
- src/BL/Services/KeycloakCommon.cs
- src/BL/Services/KeycloakTokenHelper.cs
- src/DARE-API/Program.cs
- src/DARE-API/Services/KeyclockTokenAPIHelper.cs
- src/DARE-API/appsettings.json
- src/DARE-FrontEnd/Program.cs
- src/DARE-FrontEnd/appsettings.json
- src/Data-Egress-API/Controllers/TreCredentialsController.cs
- src/Data-Egress-API/Program.cs
- src/Data-Egress-API/Services/TreClientWithoutTokenHelper.cs
- src/Data-Egress-API/appsettings.json
- src/Data-Egress-UI/Program.cs
- src/Data-Egress-UI/appsettings.json
- src/TRE-API/Controllers/DataEgressCredentialsController.cs
- src/TRE-API/Controllers/SubmissionCredentialsController.cs
- src/TRE-API/Controllers/TRECredentialsController.cs
- src/TRE-API/Program.cs
- src/TRE-API/Services/DareClientWithoutTokenHelper.cs
- src/TRE-API/Services/DataEgressClientWithoutTokenHelper.cs
- src/TRE-API/appsettings.json
- src/TRE-UI/Program.cs
- src/TRE-UI/appsettings.json
> fix Disable https required in demo

- src/DARE-API/Services/KeyclockTokenAPIHelper.cs
> Fix mistake

- src/BL/Models/Settings/BaseKeyCloakSettings.cs
- src/BL/Services/KeycloakCommon.cs
- src/BL/Services/KeycloakTokenHelper.cs
- src/DARE-API/Program.cs
- src/DARE-API/Services/KeyclockTokenAPIHelper.cs
- src/DARE-FrontEnd/Program.cs
- src/Data-Egress-API/Controllers/TreCredentialsController.cs
- src/Data-Egress-API/Program.cs
- src/Data-Egress-API/Services/TreClientWithoutTokenHelper.cs
- src/Data-Egress-UI/Program.cs
- src/TRE-API/Controllers/DataEgressCredentialsController.cs
- src/TRE-API/Controllers/SubmissionCredentialsController.cs
- src/TRE-API/Controllers/TRECredentialsController.cs
- src/TRE-API/Program.cs
- src/TRE-API/Services/DareClientWithoutTokenHelper.cs
- src/TRE-API/Services/DataEgressClientWithoutTokenHelper.cs
- src/TRE-UI/Program.cs
> fix damin it

- src/DARE-FrontEnd/Program.cs
- src/Data-Egress-UI/Program.cs
> fix: remove debugging

- src/DARE-API/Program.cs
- src/DARE-API/Repositories/DbContexts/DataInitaliser.cs
- src/Data-Egress-API/Program.cs
- src/Data-Egress-API/Repositories/DbContexts/DataInitializer.cs
- src/TRE-API/Controllers/SubmissionController.cs
- src/TRE-API/DoAgentWork.cs
- src/TRE-API/Models/AgentSettings.cs
- src/TRE-API/Program.cs
- src/TRE-API/Repositories/DbContexts/DataInitializer.cs
- src/TRE-API/Services/SubmissionHelper.cs
- src/TRE-API/appsettings.json
> Added demo mode

- src/DARE-API/Services/KeycloakMinioUserService.cs
> fix sdfsdfsd

- src/DARE-API/Services/KeycloakMinioUserService.cs
> fix: bump update

- src/Data-Egress-API/Program.cs
> fix: why didn't api build

- src/BL/Models/Settings/BaseKeyCloakSettings.cs
- src/DARE-API/Services/KeycloakMinioUserService.cs
- src/DARE-API/appsettings.json
- src/TRE-UI/Program.cs
> fix: Outstanding issues

- src/Data-Egress-API/Repositories/DbContexts/DataInitializer.cs
> fix: bump build

- src/Data-Egress-API/Controllers/DataEgressController.cs
- src/Data-Egress-API/Repositories/DbContexts/DataInitializer.cs
- src/Data-Egress-API/Services/IKeyCloakService.cs
- src/Data-Egress-UI/Controllers/DataEgressCredentialsController.cs
- src/Data-Egress-UI/Views/DataEgressCredentials/UpdateCredentials.cshtml
- src/Data-Egress-UI/Views/Shared/_Layout.cshtml
- src/TRE-API/Controllers/TRECredentialsController.cs
- src/TRE-API/Repositories/DbContexts/DataInitializer.cs
- src/TRE-API/Services/SubmissionHelper.cs
- src/TRE-UI/Controllers/TRECredentialsController.cs
- src/TRE-UI/Views/Shared/_Layout.cshtml
- src/TRE-UI/Views/TRECredentials/UpdateCredentials.cshtml
> fix: finalerrors

- src/Data-Egress-UI/Views/DataEgressCredentials/UpdateCredentials.cshtml
> fix: name changes

- .github/workflows/sonar.yaml
Updates sonar scans to be isolated to their csproj root directory. This prevents scans duplicating detections across multiple projects that all import a common project which is itself already being scanned independently.
> chore(deps): update sonar.yaml workflow

- src/TRE-API/DoAgentWork.cs
> fix: #908 Changes case of basic to BASIC for API tesk API

- .github/workflows/containers.yaml
Trigger a release to build containers after https://github.com/SwanseaUniversityMedical/DARE-Control/pull/910 merged.
> ci: trigger a release build

- src/BL/Models/Settings/BaseKeyCloakSettings.cs
- src/BL/Services/KeycloakCommon.cs
- src/BL/Services/KeycloakTokenHelper.cs
- src/DARE-API/Program.cs
- src/DARE-API/Services/KeyclockTokenAPIHelper.cs
- src/DARE-API/appsettings.json
- src/DARE-FrontEnd/Program.cs
- src/DARE-FrontEnd/appsettings.json
- src/Data-Egress-API/Controllers/TreCredentialsController.cs
- src/Data-Egress-API/Program.cs
- src/Data-Egress-API/Services/TreClientWithoutTokenHelper.cs
- src/Data-Egress-API/appsettings.json
- src/Data-Egress-UI/Program.cs
- src/Data-Egress-UI/appsettings.json
- src/TRE-API/Controllers/DataEgressCredentialsController.cs
- src/TRE-API/Controllers/SubmissionCredentialsController.cs
- src/TRE-API/Controllers/TRECredentialsController.cs
- src/TRE-API/Program.cs
- src/TRE-API/Services/DareClientWithoutTokenHelper.cs
- src/TRE-API/Services/DataEgressClientWithoutTokenHelper.cs
- src/TRE-API/appsettings.json
- src/TRE-UI/Program.cs
- src/TRE-UI/appsettings.json
> fix: add keycloak demo mode

- src/TRE-API/Controllers/ApprovalController.cs
- Encrypt password on UpdateProjects, when a user saves database credentials
- remove unused imports & format code
> fix: encrypt password in db creds

- docker-compose.yml
- vault-config/vault.hcl
> feat: vault added to docker compose

- .github/CODEOWNERS
> fix: Update CODEOWNERS so TREFX group works

- src/BL/Models/UserManagementModels.cs
- src/BL/Services/Contract/IPostgreSQLUserManagementService.cs
- src/BL/Services/PostgreSQLUserManagementService.cs
- src/TRE-API/Program.cs
> feat: postgres user management service

- src/BL/Models/ViewModels/AddiSubmissionWizard.cs
- src/BL/Services/IMinioHelper.cs
- src/BL/Services/MinioHelper.cs
- src/DARE-FrontEnd/Controllers/ProjectController.cs
- src/DARE-FrontEnd/Controllers/SubmissionController.cs
- src/DARE-FrontEnd/ViewComponents/SubmissionWizardDemoViewComponent.cs
- src/DARE-FrontEnd/Views/Project/GetProject.cshtml
- src/DARE-FrontEnd/Views/Project/SubmissionProjectDemo.cshtml
- src/DARE-FrontEnd/Views/Shared/Components/SubmissionWizardDemo/Default.cshtml
- src/DARE-FrontEnd/Views/Shared/_Layout.cshtml
- src/TRE-API/DoAgentWork.cs
- src/TRE-API/Services/SubmissionHelper.cs
- Add new Demo Wizard page that submits a Hello World example
- Simulate execution:
- tre agent picks up the job, writes Hello world stdout file to minio
- updates status
- once egress is approved submission status is updated and job is finished
- remove parts in DoAgentWork that were expecting the "image" in the TES message to be a URI, that was related to old functionality where it was accepting crates/files as the image.
> feat: demo wizard page

- README.md
> feat: Typo in readme

- src/TRE-API/DoAgentWork.cs
> fix mistake when resolving conflict

- src/Tre-Camunda/Dockerfile
> fix: camunda dockerfile updated

- src/Tre-Camunda/Dockerfile
> fix: certificates removed from dockerfile

- src/TRE-API/DoAgentWork.cs
- Removed second instance of Demo Mode code
The code block was repeated due to a conflict fixing mistake in #954 & #952 and was updating the statuses twice.
> fix: remove repeated code

- .github/workflows/containers.yaml
- .github/workflows/sonar.yaml
Update the CI to target release/nottingham as the release branch.
> ci: update containers.yaml for new release target for nottingham
